version: '3.8'
networks:
  app-tier:
    driver: bridge
services: 
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - app-tier  
    volumes: 
      - ./db/backup/files/:/data_backup/data
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - $NODEJS_LOCAL_PORT:$NODEJS_DOCKER_PORT
    environment:
      WAIT_HOSTS: mysql:3306

    networks:
      - app-tier  
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:
